
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.7.0
 * Query Engine version: 75cbdc1eb7150937890ad5465d861175c6624711
 */
Prisma.prismaVersion = {
  client: "7.7.0",
  engine: "75cbdc1eb7150937890ad5465d861175c6624711"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.CategoriesScalarFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.FeedbackScalarFieldEnum = {
  id: 'id',
  order_id: 'order_id',
  menu_item_id: 'menu_item_id',
  rating: 'rating',
  review_text: 'review_text',
  created_at: 'created_at'
};

exports.Prisma.Legacy_print_queueScalarFieldEnum = {
  id: 'id',
  order_id_pwa: 'order_id_pwa',
  table_number: 'table_number',
  total_amount: 'total_amount',
  status_print: 'status_print',
  created_at: 'created_at'
};

exports.Prisma.Menu_itemsScalarFieldEnum = {
  id: 'id',
  category_id: 'category_id',
  name: 'name',
  description: 'description',
  price: 'price',
  image_url: 'image_url',
  status: 'status'
};

exports.Prisma.Order_itemsScalarFieldEnum = {
  id: 'id',
  order_id: 'order_id',
  menu_item_id: 'menu_item_id',
  quantity: 'quantity',
  notes: 'notes'
};

exports.Prisma.OrdersScalarFieldEnum = {
  id: 'id',
  table_id: 'table_id',
  status: 'status',
  subtotal: 'subtotal',
  promo_id: 'promo_id',
  discount_amount: 'discount_amount',
  final_total: 'final_total',
  created_at: 'created_at'
};

exports.Prisma.PromotionsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  value: 'value',
  min_purchase: 'min_purchase',
  is_active: 'is_active'
};

exports.Prisma.Raw_materialsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  unit: 'unit',
  current_stock: 'current_stock',
  min_stock_alert: 'min_stock_alert'
};

exports.Prisma.Recipe_bomScalarFieldEnum = {
  id: 'id',
  menu_item_id: 'menu_item_id',
  raw_material_id: 'raw_material_id',
  quantity_required: 'quantity_required'
};

exports.Prisma.ReservationsScalarFieldEnum = {
  id: 'id',
  customer_name: 'customer_name',
  customer_phone: 'customer_phone',
  reservation_date: 'reservation_date',
  pax_count: 'pax_count',
  buffer_pax: 'buffer_pax',
  budget_type: 'budget_type',
  status: 'status',
  created_at: 'created_at'
};

exports.Prisma.TablesScalarFieldEnum = {
  id: 'id',
  table_number: 'table_number',
  qr_code_url: 'qr_code_url'
};

exports.Prisma.UsersScalarFieldEnum = {
  id: 'id',
  username: 'username',
  password_hash: 'password_hash',
  role: 'role',
  created_at: 'created_at'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.categoriesOrderByRelevanceFieldEnum = {
  name: 'name'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.feedbackOrderByRelevanceFieldEnum = {
  review_text: 'review_text'
};

exports.Prisma.menu_itemsOrderByRelevanceFieldEnum = {
  name: 'name',
  description: 'description',
  image_url: 'image_url'
};

exports.Prisma.order_itemsOrderByRelevanceFieldEnum = {
  notes: 'notes'
};

exports.Prisma.promotionsOrderByRelevanceFieldEnum = {
  name: 'name'
};

exports.Prisma.raw_materialsOrderByRelevanceFieldEnum = {
  name: 'name'
};

exports.Prisma.reservationsOrderByRelevanceFieldEnum = {
  customer_name: 'customer_name',
  customer_phone: 'customer_phone'
};

exports.Prisma.tablesOrderByRelevanceFieldEnum = {
  qr_code_url: 'qr_code_url'
};

exports.Prisma.usersOrderByRelevanceFieldEnum = {
  username: 'username',
  password_hash: 'password_hash'
};
exports.legacy_print_queue_status_print = exports.$Enums.legacy_print_queue_status_print = {
  belum_print: 'belum_print',
  sudah_print: 'sudah_print'
};

exports.menu_items_status = exports.$Enums.menu_items_status = {
  ready: 'ready',
  habis: 'habis'
};

exports.orders_status = exports.$Enums.orders_status = {
  pending: 'pending',
  preparing: 'preparing',
  ready: 'ready',
  served: 'served',
  paid: 'paid'
};

exports.promotions_type = exports.$Enums.promotions_type = {
  percent: 'percent',
  nominal: 'nominal'
};

exports.raw_materials_unit = exports.$Enums.raw_materials_unit = {
  gram: 'gram',
  ml: 'ml',
  pcs: 'pcs'
};

exports.reservations_budget_type = exports.$Enums.reservations_budget_type = {
  paket_standar: 'paket_standar',
  custom_budget: 'custom_budget'
};

exports.reservations_status = exports.$Enums.reservations_status = {
  pending_wa: 'pending_wa',
  confirmed: 'confirmed',
  completed: 'completed',
  cancelled: 'cancelled'
};

exports.users_role = exports.$Enums.users_role = {
  admin: 'admin',
  waiter: 'waiter',
  kasir: 'kasir'
};

exports.Prisma.ModelName = {
  categories: 'categories',
  feedback: 'feedback',
  legacy_print_queue: 'legacy_print_queue',
  menu_items: 'menu_items',
  order_items: 'order_items',
  orders: 'orders',
  promotions: 'promotions',
  raw_materials: 'raw_materials',
  recipe_bom: 'recipe_bom',
  reservations: 'reservations',
  tables: 'tables',
  users: 'users'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
